// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/GoCollaborate/src/collaborator/services/rpc_services.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	github.com/GoCollaborate/src/collaborator/services/rpc_services.proto

It has these top-level messages:
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import task "github.com/GoCollaborate/src/artifacts/task"
import message "github.com/GoCollaborate/src/artifacts/message"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCService service

type RPCServiceClient interface {
	Distribute(ctx context.Context, in *task.TaskPayload, opts ...grpc.CallOption) (*task.TaskPayload, error)
	Exchange(ctx context.Context, in *message.CardMessage, opts ...grpc.CallOption) (*message.CardMessage, error)
}

type rPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewRPCServiceClient(cc *grpc.ClientConn) RPCServiceClient {
	return &rPCServiceClient{cc}
}

func (c *rPCServiceClient) Distribute(ctx context.Context, in *task.TaskPayload, opts ...grpc.CallOption) (*task.TaskPayload, error) {
	out := new(task.TaskPayload)
	err := grpc.Invoke(ctx, "/services.RPCService/Distribute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServiceClient) Exchange(ctx context.Context, in *message.CardMessage, opts ...grpc.CallOption) (*message.CardMessage, error) {
	out := new(message.CardMessage)
	err := grpc.Invoke(ctx, "/services.RPCService/Exchange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCService service

type RPCServiceServer interface {
	Distribute(context.Context, *task.TaskPayload) (*task.TaskPayload, error)
	Exchange(context.Context, *message.CardMessage) (*message.CardMessage, error)
}

func RegisterRPCServiceServer(s *grpc.Server, srv RPCServiceServer) {
	s.RegisterService(&_RPCService_serviceDesc, srv)
}

func _RPCService_Distribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(task.TaskPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).Distribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.RPCService/Distribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).Distribute(ctx, req.(*task.TaskPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCService_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.CardMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.RPCService/Exchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).Exchange(ctx, req.(*message.CardMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.RPCService",
	HandlerType: (*RPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Distribute",
			Handler:    _RPCService_Distribute_Handler,
		},
		{
			MethodName: "Exchange",
			Handler:    _RPCService_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/GoCollaborate/src/collaborator/services/rpc_services.proto",
}

func init() {
	proto.RegisterFile("github.com/GoCollaborate/src/collaborator/services/rpc_services.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x31, 0x4b, 0xc0, 0x30,
	0x10, 0x85, 0x3b, 0x49, 0xc9, 0x66, 0x70, 0xca, 0xd8, 0x1f, 0x90, 0x80, 0x8a, 0x38, 0xb8, 0xd5,
	0xe2, 0x24, 0x14, 0x75, 0x97, 0x4b, 0x1a, 0xdb, 0xd0, 0xd6, 0x2b, 0x77, 0x57, 0x51, 0xf0, 0xc7,
	0x0b, 0x0d, 0x71, 0x51, 0xc4, 0xe5, 0xee, 0xde, 0x83, 0xf7, 0xdd, 0x53, 0xdd, 0x98, 0x64, 0xda,
	0xbd, 0x0d, 0xb8, 0xba, 0x3b, 0x6c, 0x71, 0x59, 0xc0, 0x23, 0x81, 0x44, 0xc7, 0x14, 0x5c, 0xf8,
	0xd6, 0x48, 0x8e, 0x23, 0xbd, 0xa5, 0x10, 0xd9, 0xd1, 0x16, 0x9e, 0x8b, 0xb0, 0x1b, 0xa1, 0xa0,
	0xae, 0x8b, 0x36, 0x57, 0x7f, 0x02, 0x81, 0x24, 0xbd, 0x40, 0x10, 0x76, 0x02, 0x3c, 0x1f, 0x23,
	0x13, 0xcc, 0xcd, 0x3f, 0x73, 0x6b, 0x64, 0x86, 0x31, 0x96, 0x9d, 0xd3, 0xe7, 0x9f, 0x4a, 0x3d,
	0xf4, 0xed, 0x63, 0x2e, 0xa1, 0x2f, 0x95, 0xba, 0x4d, 0x2c, 0x94, 0xfc, 0x2e, 0x51, 0x9f, 0xda,
	0xe3, 0xcd, 0x13, 0xf0, 0xdc, 0xc3, 0xc7, 0x82, 0x30, 0x98, 0x9f, 0x56, 0x53, 0xe9, 0x6b, 0x55,
	0x77, 0xef, 0x61, 0x82, 0xd7, 0x31, 0xea, 0x33, 0x5b, 0xf8, 0x2d, 0xd0, 0x70, 0x9f, 0x6f, 0xf3,
	0xab, 0xdb, 0x54, 0xfe, 0xe4, 0x28, 0x71, 0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x0d, 0xa7,
	0xc8, 0x4d, 0x01, 0x00, 0x00,
}
